CREATE TABLE [dbo].[Client]
(
	[ClientId] INT NOT NULL PRIMARY KEY IDENTITY(0,1),
	[Address] VARCHAR(255) NOT NULL,
	[PersonId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [dbo].[Person]([PersonId]) NOT NULL
	
)
