CREATE TABLE [dbo].[Person]
(
	[PersonId] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
	[Name] NVARCHAR(100) NOT NULL,
	[Email] NVARCHAR(255) NOT NULL,
	[Phone] NVARCHAR(30) NOT NULL,
	[Password] VARCHAR(150) NOT NULL
)
