CREATE TABLE [dbo].[Person]
(
	[PersonId] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
	[Name] NVARCHAR(100) NOT NULL,
	[Email] NVARCHAR(255) NOT NULL,
	[PhoneNumber] NVARCHAR(15) NOT NULL,
	[Password] CHAR(64) NOT NULL
)
