CREATE TABLE [dbo].[Product]
(
	[ProductId] INT NOT NULL PRIMARY KEY IDENTITY(0,1),
	[Name] NVARCHAR(100) NOT NULL,
	[Price] DECIMAL(10,2) NOT NULL,
	[Image] VARBINARY(MAX) NULL,
	[CategoryId] INT FOREIGN KEY REFERENCES [Category]([CategoryId]) NOT NULL
)
