CREATE TABLE [dbo].[User]
(
	[UserId] INT NOT NULL PRIMARY KEY IDENTITY(0,1),
	[RoleId] INT FOREIGN KEY REFERENCES [Role]([RoleId]) NOT NULL,
	[PersonId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [Person]([PersonId]) NOT NULL
)
