CREATE TABLE [dbo].[Warehouse]
(
	[WarehouseId] INT NOT NULL PRIMARY KEY DEFAULT NEWID(),
	[Name] NVARCHAR(100) NOT NULL,
	[Address] NVARCHAR(255) NOT NULL,
	[StockId] INT FOREIGN KEY REFERENCES [Stock]([StockId]) NOT NULL 
)
