CREATE TABLE [dbo].[Warehouse]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	[Name] NVARCHAR(100) NOT NULL,
	[Address] NVARCHAR(150) NOT NULL,
	[StockId] INT FOREIGN KEY REFERENCES [Stock]([Id]) NOT NULL 
)
